import turtle
print ("type the thing you want it to draw. l,k,h, and lk together are the only thing that works")
write = input()
theturtle = turtle.Turtle()
theturtle.shape("turtle")
if write == ("lk"):
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.pu()
  theturtle.forward(25)
  theturtle.pd()
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)

if write == ("h"):
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.backward(50)
if write == ("l"):
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
if write == ("k"):
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("red h"):
  theturtle.pencolor("red")
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.backward(50)
if write == ("blue k"):
  theturtle.pencolor("blue")
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("yellow l"):
  theturtle.pencolor("yellow")
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
  
  