import turtle
print ("type the thing you want it to draw, if you want to draw a flag say flag")
write = input()
if write == ("flag"):
  print("say the flag to draw it. nigeria italy france germany")
  write = input()
vertical = False
horizontal = False

theturtle = turtle.Turtle()
theturtle.shape("turtle")
def draw_italy():
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.color("black","green")
  theturtle.forward(50)
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.end_fill()
  theturtle.forward(33.333)
  theturtle.color("black","red")
  theturtle.begin_fill()
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.end_fill()

def draw_france():
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.color("black","blue")
  theturtle.forward(50)
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.end_fill()
  theturtle.forward(33.333)
  theturtle.color("black","red")
  theturtle.begin_fill()
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.end_fill()

def draw_germany():
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.backward(16.666)
  theturtle.color("black","black")
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.end_fill()
  theturtle.color("black","red")
  theturtle.begin_fill()
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.end_fill()
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.color("black","yellow")
  theturtle.begin_fill()
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.end_fill()

def draw_lithuania():
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.backward(16.666)
  theturtle.color("black","yellow")
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.end_fill()
  theturtle.color("black","green")
  theturtle.begin_fill()
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.end_fill()
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.color("black","red")
  theturtle.begin_fill()
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.end_fill()

def draw_russia():
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.backward(16.666)
  theturtle.color("black","white")
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.end_fill()
  theturtle.color("black","blue")
  theturtle.begin_fill()
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.end_fill()
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.color("black","red")
  theturtle.begin_fill()
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.left(90)
  theturtle.forward(16.666)
  theturtle.left(90)
  theturtle.forward(100)
  theturtle.end_fill()
  
def draw_nigeria():
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.color("black","green")
  theturtle.forward(50)
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.end_fill()
  theturtle.forward(33.333)
  theturtle.color("black","green")
  theturtle.begin_fill()
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.end_fill()

#flags
if write == ("italy"):
  draw_italy()

if write == ("nigeria"):
  draw_nigeria()

if write == ("france"):
  draw_france()

if write == ("germany"):
  draw_germany()

if write == ("russia"):
  draw_russia()

if write == ("lithuania"):
  draw_lithuania()

if write == ("custom"):
  print ("whats the first color")
  color1 = input()
  print ("whats the second color")
  color2 = input()
  print ("whats the third color")
  color3 = input()
  if vertical == True:
    theturtle.pencolor("black")
    theturtle.forward(100)
    theturtle.right(90)
    theturtle.forward(50)
    theturtle.right(90)
    theturtle.forward(100)
    theturtle.right(90)
    theturtle.forward(50)
    theturtle.right(90)
    theturtle.forward(33.333)
    theturtle.right(90)
    theturtle.color("black",color1)
    theturtle.forward(50)
    theturtle.begin_fill()
    theturtle.right(90)
    theturtle.forward(33.333)
    theturtle.right(90)
    theturtle.forward(50)
    theturtle.right(90)
    theturtle.forward(33.333)
    theturtle.end_fill()
    theturtle.forward(33.333)
    theturtle.color("black",color3)
    theturtle.begin_fill()
    theturtle.forward(33.334)
    theturtle.right(90)
    theturtle.forward(50)
    theturtle.right(90)
    theturtle.forward(33.334)
    theturtle.right(90)
    theturtle.forward(50)
    theturtle.end_fill()
      
  
  



if write == ("lk"):
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.pu()
  theturtle.forward(25)
  theturtle.pd()
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("h"):
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.backward(50)
if write == ("l"):
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
if write == ("k"):
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("red h"):
  theturtle.pencolor("red")
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.backward(50)
if write == ("blue k"):
  theturtle.pencolor("blue")
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("yellow l"):
  theturtle.pencolor("yellow")
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
  
  