import turtle
print ("type the thing you want it to draw.")
write = input()
theturtle = turtle.Turtle()
theturtle.shape("turtle")
if write == ("italy"):
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.color("black","green")
  theturtle.forward(50)
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.end_fill()
  theturtle.forward(33.333)
  theturtle.color("black","red")
  theturtle.begin_fill()
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.end_fill()

def drawnigeria
  theturtle.pencolor("black")
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(100)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.color("black","green")
  theturtle.forward(50)
  theturtle.begin_fill()
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.333)
  theturtle.end_fill()
  theturtle.forward(33.333)
  theturtle.color("black","green")
  theturtle.begin_fill()
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.right(90)
  theturtle.forward(33.334)
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.end_fill()

    
  



if write == ("lk"):
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.pu()
  theturtle.forward(25)
  theturtle.pd()
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("h"):
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.backward(50)
if write == ("l"):
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
if write == ("k"):
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("red h"):
  theturtle.pencolor("red")
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
  theturtle.left(90)
  theturtle.forward(25)
  theturtle.backward(50)
if write == ("blue k"):
  theturtle.pencolor("blue")
  theturtle.left(90)
  theturtle.forward(50)
  theturtle.backward(25)
  theturtle.right(45)
  theturtle.forward(25)
  theturtle.backward(25)
  theturtle.right(90)
  theturtle.forward(25)
if write == ("yellow l"):
  theturtle.pencolor("yellow")
  theturtle.right(90)
  theturtle.forward(50)
  theturtle.left(90)
  theturtle.forward(25)
  
  